[package]
name = "mx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0.51"
zune-inflate = "0"
